"""Şirket seviyesi belge spec'leri (Phase 3.1 + 5.1)."""

from __future__ import annotations

from seed_data.generator.document_specs._base import DocumentSpec

SPECS: dict[str, DocumentSpec] = {
    "DOC-CO-ADM-001": DocumentSpec(
        doc_id="DOC-CO-ADM-001",
        family="letter",
        subtitle_tr="Yönetim Kurulu Kararı",
        subtitle_en="",
        section_headings_tr=["Karar Gerekçesi", "Alınan Karar"],
        section_headings_en=[],
        signature_roles_tr=["Yönetim Kurulu Başkanı", "Yönetim Kurulu Üyesi"],
        subject_label_tr="Ankara RES Finansman Onayı",
    ),
    "DOC-CO-ADM-002": DocumentSpec(
        doc_id="DOC-CO-ADM-002",
        family="letter",
        subtitle_tr="Yönetim Kurulu Kararı",
        subtitle_en="",
        section_headings_tr=["Karar Gerekçesi", "Alınan Karar"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="İzmir RES Geliştirme Bütçesi Onayı",
    ),
    "DOC-CO-ADM-003": DocumentSpec(
        doc_id="DOC-CO-ADM-003",
        family="letter",
        subtitle_tr="Pay Sahipleri Kararı",
        subtitle_en="",
        section_headings_tr=["Karar Gerekçesi", "Alınan Karar"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="GHI Yatırım A.Ş. Ortaklık Onayı",
    ),
    "DOC-CO-ADM-004": DocumentSpec(
        doc_id="DOC-CO-ADM-004",
        family="report",
        subtitle_tr="Şirketler Grubu — Sigorta Programı Özeti",
        subtitle_en="",
        section_headings_tr=["Kapsam Özeti", "Poliçe Dönemi"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-CO-ADM-005": DocumentSpec(
        doc_id="DOC-CO-ADM-005",
        family="report",
        subtitle_tr="Şirketler Grubu — Yıllık Yönetim Raporu",
        subtitle_en="",
        section_headings_tr=["Genel Değerlendirme", "Sonuç"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-CO-ADM-006": DocumentSpec(
        doc_id="DOC-CO-ADM-006",
        family="agreement",
        subtitle_tr="Şirketler Grubu İlişkili Taraf Hizmet Sözleşmesi",
        subtitle_en="",
        section_headings_tr=["1. Hizmetlerin Kapsamı", "2. Yürürlük ve Genel Hükümler"],
        section_headings_en=[],
        signature_roles_tr=["İmza: [[spv_name]] Yetkilisi", "İmza: [[counterparty]] Yetkilisi"],
    ),
    "DOC-CO-ADM-007": DocumentSpec(
        doc_id="DOC-CO-ADM-007",
        family="report",
        subtitle_tr="Şirketler Grubu — Kurumsal Yönetim ve Uyum Politikası",
        subtitle_en="",
        section_headings_tr=["Politika Kapsamı", "Uygulama"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-CO-ADM-008": DocumentSpec(
        doc_id="DOC-CO-ADM-008",
        family="letter",
        subtitle_tr="Yönetim Kurulu Kararı",
        subtitle_en="",
        section_headings_tr=["Karar Gerekçesi", "Alınan Karar"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="Denetim Komitesi Ataması",
    ),
    "DOC-CO-ADM-009": DocumentSpec(
        doc_id="DOC-CO-ADM-009",
        family="report",
        subtitle_tr="Şirketler Grubu — Risk Raporu",
        subtitle_en="",
        section_headings_tr=["Risk Değerlendirmesi", "Sonuç"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-CO-ADM-010": DocumentSpec(
        doc_id="DOC-CO-ADM-010",
        family="letter",
        subtitle_tr="Pay Sahipleri Kararı",
        subtitle_en="",
        section_headings_tr=["Karar Gerekçesi", "Alınan Karar"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="Kâr Dağıtım Politikası",
    ),
}
