"""Kızılova RES — belge spec'leri (Phase 3.1 + 5.1)."""

from __future__ import annotations

from seed_data.generator.document_specs._base import DocumentSpec, ExtraTable

SPECS: dict[str, DocumentSpec] = {
    "DOC-IZM-DEV-001": DocumentSpec(
        doc_id="DOC-IZM-DEV-001",
        family="letter",
        subtitle_tr="Kızılova RES Rüzgar Enerjisi Projesi",
        subtitle_en="",
        section_headings_tr=["Önlisans Kapsamı", "Süreç ve Yükümlülükler"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: Lisanslama Uzmanı", "Onaylayan: Kurum Yetkilisi"],
        subject_label_tr="Önlisans — [[project_name]]",
    ),
    "DOC-IZM-DEV-002": DocumentSpec(
        doc_id="DOC-IZM-DEV-002",
        family="report",
        subtitle_tr="Kızılova RES — Arazi Edinim Durum Raporu",
        subtitle_en="",
        section_headings_tr=["Arazi Edinim Süreci", "Güncel Durum"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: Arazi ve İzinler Uzmanı", "Kontrol Eden: Proje Müdürü"],
    ),
    "DOC-IZM-DEV-003": DocumentSpec(
        doc_id="DOC-IZM-DEV-003",
        family="letter",
        subtitle_tr="Kızılova RES ÇED Süreci",
        subtitle_en="",
        section_headings_tr=["Süreç Durumu", "Bekleyen Adımlar"],
        section_headings_en=[],
        extra_table=ExtraTable(
            heading_tr="Bekleyen Kritik Adımlar", heading_en="", kind="pending_steps"
        ),
        signature_roles_tr=["Hazırlayan: Çevre ve İzinler Uzmanı", "Onaylayan: Proje Müdürü"],
        subject_label_tr="ÇED Süreci Durum Bilgisi — [[project_name]]",
    ),
    "DOC-IZM-DEV-004": DocumentSpec(
        doc_id="DOC-IZM-DEV-004",
        family="report",
        subtitle_tr="Kızılova RES — Rüzgar Kaynağı ve Ön Fizibilite Teknik Raporu",
        subtitle_en="",
        section_headings_tr=[
            "Rüzgar Kaynağı Değerlendirmesi",
            "Ön Fizibilite Sonuçları",
            "Öneriler",
        ],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: Teknik Danışman", "Kontrol Eden: Proje Müdürü"],
    ),
    "DOC-IZM-DEV-005": DocumentSpec(
        doc_id="DOC-IZM-DEV-005",
        family="letter",
        subtitle_tr="Kızılova RES Şebeke Bağlantısı",
        subtitle_en="",
        section_headings_tr=["Başvuru Kapsamı", "Süreç"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="Bağlantı Görüşü Başvurusu — [[project_name]]",
    ),
    "DOC-IZM-DEV-006": DocumentSpec(
        doc_id="DOC-IZM-DEV-006",
        family="report",
        subtitle_tr="Kızılova RES — Halkın Katılımı Toplantısı",
        subtitle_en="",
        section_headings_tr=["Toplantı Özeti", "Alınan Görüşler"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-DEV-007": DocumentSpec(
        doc_id="DOC-IZM-DEV-007",
        family="report",
        subtitle_tr="Kızılova RES — Rüzgar Ölçüm Kampanyası Raporu",
        subtitle_en="",
        section_headings_tr=["Ölçüm Kapsamı", "Sonuçlar"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-DEV-008": DocumentSpec(
        doc_id="DOC-IZM-DEV-008",
        family="letter",
        subtitle_tr="Kızılova RES Askeri Yasak Bölge Görüşü",
        subtitle_en="",
        section_headings_tr=["Talep Kapsamı", "Süreç"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="Askeri Yasak Bölgeler Ön Görüş Talebi — [[project_name]]",
    ),
    "DOC-IZM-LEG-001": DocumentSpec(
        doc_id="DOC-IZM-LEG-001",
        family="report",
        subtitle_tr="Kızılova RES — Arazi Mülkiyeti Hukuki İnceleme Notu",
        subtitle_en="",
        section_headings_tr=["İnceleme Kapsamı", "Değerlendirme"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-LEG-002": DocumentSpec(
        doc_id="DOC-IZM-LEG-002",
        family="agreement",
        subtitle_tr="Kızılova RES Kira/İrtifak Hakkı Sözleşmesi (Taslak)",
        subtitle_en="",
        section_headings_tr=["1. Hakkın Kapsamı", "2. Yürürlük ve Genel Hükümler"],
        section_headings_en=[],
        signature_roles_tr=["İmza: [[spv_name]] Yetkilisi", "İmza: [[counterparty]] Yetkilisi"],
    ),
    "DOC-IZM-LEG-003": DocumentSpec(
        doc_id="DOC-IZM-LEG-003",
        family="report",
        subtitle_tr="Kızılova RES — Şirket Yapısı Hukuki Görüşü",
        subtitle_en="",
        section_headings_tr=["İnceleme Kapsamı", "Değerlendirme"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-LEG-004": DocumentSpec(
        doc_id="DOC-IZM-LEG-004",
        family="report",
        subtitle_tr="Kızılova RES — Önlisans Süre Uzatımı Değerlendirmesi",
        subtitle_en="",
        section_headings_tr=["Değerlendirme Kapsamı", "Sonuç"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-ADM-001": DocumentSpec(
        doc_id="DOC-IZM-ADM-001",
        family="letter",
        subtitle_tr="Kızılova RES Geliştirme Bütçesi",
        subtitle_en="",
        section_headings_tr=["Bütçe Kapsamı", "Onay"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Onaylayan: Yetkili Makam"],
        subject_label_tr="Geliştirme Bütçesi Onayı — [[project_name]]",
    ),
    "DOC-IZM-ADM-002": DocumentSpec(
        doc_id="DOC-IZM-ADM-002",
        family="report",
        subtitle_tr="Kızılova RES — Saha Güvenliği ve İdari Düzenlemeler Notu",
        subtitle_en="",
        section_headings_tr=["Düzenleme Kapsamı", "Değerlendirme"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
    "DOC-IZM-ADM-003": DocumentSpec(
        doc_id="DOC-IZM-ADM-003",
        family="report",
        subtitle_tr="Kızılova RES — Proje Maliyet Takip Notu",
        subtitle_en="",
        section_headings_tr=["Maliyet Kapsamı", "Değerlendirme"],
        section_headings_en=[],
        signature_roles_tr=["Hazırlayan: İlgili Birim", "Kontrol Eden: Departman Yöneticisi"],
    ),
}
