// Every user-facing string of the UI. Backend error bodies (`detail`) are already
// Turkish (SPEC_02 §13) and are shown verbatim — they are not re-translated here.
export const S = {
  app: "Company AI",
  loading: "Yükleniyor…",
  nav: { home: "Ana sayfa", ask: "Genel Sor", logout: "Çıkış" },
  login: {
    title: "Giriş",
    username: "Kullanıcı adı",
    password: "Şifre",
    submit: "Giriş yap",
    submitting: "Giriş yapılıyor…",
  },
  home: {
    title: "Departmanlar",
    noDepartments: "Erişebildiğiniz bir departman yok.",
    askTitle: "Genel Sor",
    askHint: "Yetkinizin izin verdiği tüm belgelerde arar.",
    askButton: "Soru sor",
  },
  department: {
    tabs: { ask: "AI'ya Sor", documents: "Belgeler", upload: "Belge Yükle", projects: "Projeler" },
    subAll: "Tümü",
    subNote:
      "Alt departman seçimi yalnızca belge listesini filtreler; sorular departmanın tamamında arar.",
    notFound: "Departman bulunamadı.",
  },
  ask: {
    generalTitle: "Genel Sor",
    scopeNote: (name: string) => `Yalnızca ${name} belgelerinde arar.`,
    placeholder: "Sorunuzu yazın",
    submit: "Sor",
    submitting: "Cevap bekleniyor…",
    examples: "Örnek:",
    exampleQuestions: [
      "Ankara RES'in güncel minimum DSCR covenant'ı nedir?",
      "Ankara RES Facility Agreement'ının ilk vadesi kaç yıldı?",
      "İzmir RES'in COD tarihi nedir?",
    ],
    answerTitle: "Cevap",
    sourcesTitle: "Kaynaklar",
    noSources: "Kaynak gösterilmedi.",
    current: "GÜNCEL",
    page: "Sayfa",
    version: "Versiyon",
    date: "Tarih",
    effective: "Yürürlük",
    supersedes: (title: string) => `"${title}" belgesini değiştirir`,
    supersededBy: (title: string) => `"${title}" tarafından değiştirildi`,
    project: "Proje",
    model: "Model",
    tokens: "token",
    download: "Belgeyi indir",
  },
  documents: {
    title: "Belgeler",
    empty: "Bu kapsamda belge yok.",
    columns: {
      title: "Başlık",
      type: "Tür",
      counterparty: "Muhatap",
      date: "Tarih",
      status: "Durum",
      confidentiality: "Gizlilik",
      ingestion: "İşlem",
      project: "Proje",
      subdepartment: "Alt departman",
    },
    download: "İndir",
    detail: "Belge detayı",
    close: "Kapat",
    tags: "Etiketler",
    effectiveDate: "Yürürlük tarihi",
    version: "Versiyon",
    supersedes: "Değiştirdiği belge",
    supersededBy: "Yerini alan belge",
    pages: "Sayfa sayısı",
    ingestionError: "İşlem hatası",
    none: "—",
  },
  upload: {
    title: "Belge Yükle",
    file: "Dosya (pdf, png, jpg)",
    titleField: "Başlık",
    type: "Belge türü",
    counterparty: "Muhatap",
    date: "Belge tarihi",
    status: "Durum",
    confidentiality: "Gizlilik",
    project: "Proje",
    projectNone: "Proje yok",
    subdepartment: "Alt departman",
    subNone: "Belirtilmedi",
    effectiveDate: "Yürürlük tarihi (opsiyonel)",
    version: "Versiyon",
    supersedes: "Şu belgeyi değiştirir (opsiyonel)",
    supersedesNone: "Yok",
    submit: "Yükle",
    submitting: "Yükleniyor…",
    processing: "Belge işleniyor (OCR ve metin çıkarma)…",
    ready: "Belge hazır.",
    failed: "Belge işlenirken hata oluştu:",
    another: "Yeni belge yükle",
  },
  suggestion: {
    title: "AI metadata önerisi",
    waiting: "Öneri hazırlanıyor… (arka planda, genellikle 15 saniye içinde)",
    notYet: "Bu belge için henüz öneri yok.",
    generate: "Şimdi üret",
    retry: "Tekrar dene",
    failed: "Öneri üretilemedi:",
    apply: "Seçilenleri uygula",
    reject: "Reddet",
    adminOnly: "Öneriyi yalnızca yönetici uygulayabilir.",
    includeHint: "Yalnızca işaretlenen alanlar belgeye yazılır; diğerleri dokunulmadan kalır.",
    nothingSelected: "Uygulanacak alan seçilmedi.",
    suggested: "Önerilen",
    currentValue: "Mevcut",
    confidence: "güven",
    model: "Model",
    status: {
      pending: "Bekliyor",
      applied: "Uygulandı",
      rejected: "Reddedildi",
      failed: "Hata",
    },
  },
  projects: {
    title: "Projeler",
    empty: "Bu departmana bağlı proje yok.",
    columns: { name: "Ad", code: "Kod", stage: "Aşama", active: "Durum" },
    active: "Aktif",
    inactive: "Pasif",
    new: "Yeni proje",
    edit: "Düzenle",
    cancel: "Vazgeç",
    save: "Kaydet",
    saving: "Kaydediliyor…",
    name: "Proje adı",
    code: "Proje kodu (örn. ANK_RES)",
    stage: "Aşama",
    departments: "Departmanlar",
    isActive: "Aktif",
  },
  errors: {
    network: "Sunucuya ulaşılamadı.",
    generic: "Beklenmeyen bir hata oluştu.",
    requestId: "İstek no",
  },
} as const;
